### PR TITLE
chore: remove twitter & add fackbook icon

### LINKED ISSUE #4: Remove the personal Twitter account
Please remove the personal Twitter account
https://github.com/iii-cutting-edge-tech-lab/old-buddies-website/blob/main/config.toml#L19

Or maybe can reference to `III Old Buddies` Facebook group URL?
https://www.facebook.com/groups/349727092633390

### PR DESCRIPTION
**Pull request by neilkuan**
close #4

### CODE REVIEW

**Review by RicoToothless — COMMENTED** [review]
Why is using hardcode instead of to refer to `config.toml`?

**Comment by neilkuan** [comment]
because [example](https://github.com/runningstream/hugograyscale/#shortcodes) is hardcode ...

**Comment by RicoToothless** [comment]
I think the matter is project maintainability. Just image it, if I merged this pull request, the new developer would ask the same question like:
"Why `social` can be config on multi-place?"
"Why the `social` section in `config.toml` is not workable?"

**Comment by neilkuan** [comment]
Updated !!
- remove jane themes.
- fix session image resize for all devices.
- update README.md.
- fix hardcode in social.
 @RicoToothless  ,please review .

**Pull request closed without merging**
